apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: yaoshunyu/z-flask-app
    newTag: 0121392c37941029130c0651786c181d1407ef7f

replicas:
  - name: z-flask-app
    count: 1
