apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: yaoshunyu/z-flask-app
    newTag: 5740433efc2d915d6c7baf1897aa47be4bc2a7e0

replicas:
  - name: z-flask-app
    count: 1
