apiVersion: apps/v1
kind: Deployment
metadata:
  name: z-flask-app
spec:
  selector:
    matchLabels:
      app: z-flask-app
  template:
    metadata:
      labels:
        app: z-flask-app
    spec:
      containers:
        - name: app
          image: yaoshunyu/z-flask-app:latest
          ports:
            - containerPort: 5000
